### ISSUE TITLE
Add Docker and Docker Compose to Express API

### ISSUE THREAD

**Issue by arya2004** [arya2004/pulseGuard#5]
We need to containerize our Express.js API using Docker and Docker Compose to streamline the development, testing, and deployment process. This will ensure consistency across different environments and simplify dependency management.

**Acceptance Criteria:**
1. Dockerfile should be created to define the environment for the Express.js application.
2. Docker Compose file should be created to orchestrate the Docker container for the Express.js app.
3. Docker setup should allow for easy local development, with hot reloading enabled.
4. Documentation should be updated to include setup and usage instructions for Docker and Docker Compose.

**Tasks:**
- [ ] **Create a Dockerfile:**

- [ ] **Create a Docker Compose file (`docker-compose.yml`):**

- [ ] **Enable hot-reloading for local development:**

- [ ] **Update documentation:**

**Comment by geekyharsh05** [comment]
@arya2004 Can you please assign this to me?

**Comment by geekyharsh05** [comment]
@arya2004 ?

**Comment by arya2004** [comment]
apologies for late reply, you can go ahead with this issue

**Comment by geekyharsh05** [comment]
@arya2004 Thanks

**Comment by geekyharsh05** [comment]
@arya2004 Can you please tell me why in the local `npm install` is not working
<img width="926" alt="Screenshot 2024-10-04 at 9 10 34 PM" src="https://github.com/user-attachments/assets/876dbd07-3835-4f68-b389-aebe29de6e69">

**Comment by arya2004** [comment]
@geekyharsh05 it is working on Windows 10 with Node version v20.10.0

Probably it is because of different OS?

![image](https://github.com/user-attachments/assets/bc2848d1-b041-43db-8177-ed251a7decf0)

**Comment by PiyushXCoder** [comment]
We need to pick specific version of node

**Comment by geekyharsh05** [comment]
> We need to pick specific version of node

Using engines in package.json??

**Comment by pandeyashu08** [comment]
@arya2004 @geekyharsh05 It is also not working on windows
![Screenshot 2024-10-04 220917](https://github.com/user-attachments/assets/0014df2a-609a-4d76-9f37-1fefa06fd5a9)

**Comment by arya2004** [comment]
`node-gpy` requires Python 2.xx (especially 2.7) not 3.xx 

Source- https://www.npmjs.com/package/node-gyp/v/3.8.0

![image](https://github.com/user-attachments/assets/f16890c2-98df-45ed-a3a1-da567c632484)
